#! /bin/sh

SED="/bin/sed"
prefix="/home/zeyu/Workspace/code/source/php-5.6.3/objs"
datarootdir="/home/zeyu/Workspace/code/source/php-5.6.3/objs/php"
exec_prefix="${prefix}"
version="5.6.3"
vernum="50603"
include_dir="${prefix}/include/php"
includes="-I$include_dir -I$include_dir/main -I$include_dir/TSRM -I$include_dir/Zend -I$include_dir/ext -I$include_dir/ext/date/lib"
ldflags=" -L/usr/lib/i386-linux-gnu"
libs="-lcrypt   -lz -lresolv -lcrypt -lrt -lmcrypt -lltdl -lpng -lz -ljpeg -lcurl -lbz2 -lz -lrt -lm -ldl -lnsl  -lxml2 -lcurl -lxml2 -lxml2 -lcrypt -lxml2 -lxml2 -lxml2 -lcrypt "
extension_dir='/home/zeyu/Workspace/code/source/php-5.6.3/objs/lib/php/extensions/no-debug-non-zts-20131226'
man_dir=`eval echo ${datarootdir}/man`
program_prefix=""
program_suffix=""
exe_extension=""
php_cli_binary=NONE
php_cgi_binary=NONE
configure_options=" '--prefix=/home/zeyu/Workspace/code/source/php-5.6.3/objs' '--enable-fpm' '--with-mcrypt=/usr/local/libmcrypt' '--with-zlib' '--enable-mbstring' '--with-mysql' '--with-mysqli' '--with-mysql-sock' '--with-gd' '--with-jpeg-dir=/usr/lib' '--enable-gd-native-ttf' '--enable-pdo' '--with-gettext' '--with-curl' '--with-pdo-mysql' '--enable-sockets' '--enable-bcmath' '--enable-xml' '--with-bz2' '--enable-zip' '--enable-mysqli' '--disable-fileinfo'"
php_sapis=" cli fpm cgi"

# Set php_cli_binary and php_cgi_binary if available
for sapi in $php_sapis; do
  case $sapi in
  cli)
    php_cli_binary="${exec_prefix}/bin/${program_prefix}php${program_suffix}${exe_extension}"
    ;;
  cgi)
    php_cgi_binary="${exec_prefix}/bin/${program_prefix}php-cgi${program_suffix}${exe_extension}"
    ;;
  esac
done

# Determine which (if any) php binary is available
if test "$php_cli_binary" != "NONE"; then
  php_binary="$php_cli_binary"
else
  php_binary="$php_cgi_binary"
fi

# Remove quotes
configure_options=`echo $configure_options | $SED -e "s#'##g"`

case "$1" in
--prefix)
  echo $prefix;;
--includes)
  echo $includes;;
--ldflags)
  echo $ldflags;;
--libs)
  echo $libs;;
--extension-dir)
  echo $extension_dir;;
--include-dir)
  echo $include_dir;;
--php-binary)
  echo $php_binary;;
--php-sapis)
  echo $php_sapis;;
--configure-options)
  echo $configure_options;;
--man-dir)
  echo $man_dir;;
--version)
  echo $version;;
--vernum)
  echo $vernum;;
*)
  cat << EOF
Usage: $0 [OPTION]
Options:
  --prefix            [$prefix]
  --includes          [$includes]
  --ldflags           [$ldflags]
  --libs              [$libs]
  --extension-dir     [$extension_dir]
  --include-dir       [$include_dir]
  --man-dir           [$man_dir]
  --php-binary        [$php_binary]
  --php-sapis         [$php_sapis]
  --configure-options [$configure_options]
  --version           [$version]
  --vernum            [$vernum]
EOF
  exit 1;;
esac

exit 0
